// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsVHGx_2UGwnX67A3y1HtYDcxMq_nfp14',
    appId: '1:552133324490:web:59076198d86a137eb14e33',
    messagingSenderId: '552133324490',
    projectId: 'lab8-027',
    authDomain: 'lab8-027.firebaseapp.com',
    storageBucket: 'lab8-027.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnTzs3TQfUlRFnQ8x6xBBi61sno5cX8qg',
    appId: '1:552133324490:android:820cec7eb2ce84ceb14e33',
    messagingSenderId: '552133324490',
    projectId: 'lab8-027',
    storageBucket: 'lab8-027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx3AOy-82oUDaN8svRt3DxO1ON7TDmQog',
    appId: '1:552133324490:ios:5d46c3e68e9fa05db14e33',
    messagingSenderId: '552133324490',
    projectId: 'lab8-027',
    storageBucket: 'lab8-027.firebasestorage.app',
    iosClientId: '552133324490-sidh14oibkon2snoc3qfc2e3fqd5u88e.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab8027',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx3AOy-82oUDaN8svRt3DxO1ON7TDmQog',
    appId: '1:552133324490:ios:5d46c3e68e9fa05db14e33',
    messagingSenderId: '552133324490',
    projectId: 'lab8-027',
    storageBucket: 'lab8-027.firebasestorage.app',
    iosClientId: '552133324490-sidh14oibkon2snoc3qfc2e3fqd5u88e.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab8027',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsVHGx_2UGwnX67A3y1HtYDcxMq_nfp14',
    appId: '1:552133324490:web:73b1475113f16644b14e33',
    messagingSenderId: '552133324490',
    projectId: 'lab8-027',
    authDomain: 'lab8-027.firebaseapp.com',
    storageBucket: 'lab8-027.firebasestorage.app',
  );
}
